server:
  port: 8086

spring:
  datasource:

    url: jdbc:sqlserver://localhost:1433;databaseName=demo_db;encrypt=true;trustServerCertificate=true

    username: sa
    password: Admin12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none 
    show-sql: true
    properties:
      hibernate.format_sql: true 
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  #init:
  #mode: always
